<a href="https://colab.research.google.com/github/yahia-kplr/Machine-Learning-workshop/blob/master/03%20-%20USE%20CASE/House%20Price%20Prediction%20-%20Exercice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <center>House Prices Prediction</center>

We are going to work on a dataset which consists information about the location of the house, price and other aspects such as square feet etc.<br>
Our main aim today is to make a model which can give us a good prediction on the price of the house based on other variables.

#### Import neccessary libraries :

In [2]:
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

#### Load the dataset from the file kc_house_data.csv :

In [1]:
# Fill here

Field | Meaning
--- | ---
**id** | `A notation for a house`
**date** | `Date house was sold`
**price** | `Price is prediction target`
**bedrooms** | `Number of Bedrooms/House`
**bathrooms** | `Number of bathrooms/bedrooms`
**sqft_living** | `Square footage of the home`
**sqft_lot** | `Square footage of the lot`
**floors** | `Total floors (levels) in house`
**waterfront** | `House which has a view to a waterfront`
**view** | `Has been viewed`
**condition** | `How good the condition is Overall`
**grade** | `Overall grade given to the housing unit, based on King County grading system`
**sqft_above** | `Square footage of house apart from basement`
**sqft_basement** | `Square footage of the basement`
**yr_built** | `Built Year`
**yr_renovated** | `Year when house was renovated`
**zipcode** | `Zip code`
**lat** | `Latitude coordinate`
**long** | `Longitude coordinate`
**sqft_living15** | `Living room area in 2015(implies-- some renovations) This might or might not have affected the lotsize area`
**sqft_lot15** | `Lot size area in 2015 (implies-- some renovations)`

#### Explore dataset :
Use describe function to see the percentile’s and other key statistics.

In [ ]:
data.describe()

* The dataset has a house where the house has 33 bedrooms.
* Maximum square feet is 13,450 where as the minimum is 290.
* ...

#### Which is the most common house (Bedroom wise) ?

In [ ]:
data['bedrooms'].value_counts().plot(kind='bar')
plt.title("Number of Bedroom")
plt.xlabel("Bedrooms")
plt.ylabel("Count")

#### Visualizing the location of the houses based on latitude and longitude :

We will use **Seaborn**.<br>
It is a Python data visualization library based on matplotlib and provides a high-level interface for drawing attractive and informative statistical graphics.

In [ ]:
import seaborn as sns

plt.figure(figsize=(10,10))
sns.jointplot(x=data.lat.values, y=data.long.values, height=10)
plt.ylabel('Longitude', fontsize=12)
plt.xlabel('Latitude', fontsize=12)
plt.show()

#### How common factors are affecting the price of the houses ?

1. Location :

In [ ]:
plt.scatter(data.long, data.price)
plt.xlabel("Longitude")
plt.ylabel("Price")
plt.title("Price vs Location of the area")

In [ ]:
plt.scatter(data.lat, data.price)
plt.xlabel("Latitude")
plt.ylabel("Price")
plt.title("Latitude vs Price")

2. Living area :

In [4]:
# Fill here

3. Bedrooms :

In [ ]:
# Fill here

4. Square Footage :

In [ ]:
# Fill here

5. View to a waterfront :

In [ ]:
plt.scatter(data.waterfront, data.price)
plt.xlabel("Price")
plt.title("Waterfront vs Price (0 = no waterfront)")
plt.show()

6. Zip code :

In [ ]:
plt.scatter(data.zipcode, data.price)
plt.xlabel("Price")
plt.ylabel("Zip Code")
plt.title("Which is the pricey location by zipcode?")
plt.show()

#### Heatmap :
Making sure we covered all the relations, we plot a correlation between all the features using a heatmap.

A heatmap is a two-dimensional graphical representation of data where the individual values that are contained in a matrix are represented as colors.

In [ ]:
fig ,ax = plt.subplots(figsize=(20, 15))
colormap = sns.diverging_palette(220, 10, as_cmap=True)
sns.heatmap(data.corr(), annot=True, cmap=colormap)

#### Model :
1. Create the linear regression model.
2. Normalization : Convert date to boolean (2014 to 1 and 2015 to 0).
3. Clean data useless features...

In [4]:
# Fill here

In [38]:
data.tail()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,1,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,0,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,1,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,0,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,1,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

4. Split data.
5. Train the model.
6. Calculate the score.

In [5]:
from sklearn.model_selection import train_test_split

# x_train , x_test , y_train , y_test

#### To improve the result choose another mode:
1. Create the model.<br>
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html

In [7]:
# Fill here

2. Train the model.
3. Calculate the score.

In [8]:
# Fill here

In [ ]:
4. Make predictions :

In [ ]:
# Fill here